version: "3"

services:
  backend:
    image: gcr.io/stoked-magpie-351406/bedep
    ports:
      - "30002:30002"

  frontend:
    image: gcr.io/stoked-magpie-351406/fedep
    ports:
      - "80:30001"
    environment:
      API_URL: backend:30002