name: Docker Image CD

on:
  push:
    branches: [ master, dev, f#37 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd backend
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
