name: Docker Image CD

on:
  push:
    branches: [ master, dev, f#37 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: get branch name test
      run: |
        echo running on branch ${GITHUB_REF##*/}